spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/wallet_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  error:
    include-stacktrace: never